// <auto-generated />
using System;
using DemoRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoRM.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201024101148_initial Create")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoRM.Models.Customer", b =>
                {
                    b.Property<int>("LOG_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Active_Time_Log")
                        .HasColumnType("datetime2");

                    b.Property<int>("CUS_ID")
                        .HasColumnType("int");

                    b.Property<string>("Product_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SHOP_ID")
                        .HasColumnType("int");

                    b.HasKey("LOG_ID");

                    b.ToTable("tbl_customer");
                });
#pragma warning restore 612, 618
        }
    }
}
